language: node_js
node_js:
- node
install:
- npm i
- npm i -g codecov
script:
- npm run lint
- npm run build
- npm run ci
deploy:
  skip_cleanup: true
  provider: npm
  email: obfishstudio@gmail.com
  on:
    tags: false
    repo: jjyyxx/JSONSchemaSimulator
    branch: develop
