language: node_js
node_js:
- node
install:
- npm i
- npm i -g codecov
script:
- npm run lint
- npm run build
- npm run ci
deploy:
  provider: npm
  email: obfishstudio@gmail.com
  api_key:
    secure: mgQCFzGgGrnz8AigsQK6hxPvLYGqoNpwZcST076m+f2BBJoZd3tCqWIdT0y11g53VNyCkC+RHl8UE1iNcy23mlhCEybzXqH1HE/ZxqtBkebDwGj5P9xuXH6X4qlAXzqQ+MFRxpq+ttwz2k4coofRrnqLVRc/v+Io4D5vUwEkp5qNJFxNmkr28KJNsq9NiiSP9NT+pb+E/HgGIsnFOKgA9W2W2iutS/QaP0QibOgjTn1iPiSAcZMYkSCM4ehp8apWe9LM7sTe18sUC6N8C9uSvGNC7jJjV9/EKbU+U3klQG5qY/9YCMDqhgecz/V7aEjIvRPl7C/XOfOLN+A1Ypfc6DF/Z2DRHOD2Z0Lo9+MuF/jL4y8QuPTgdwaczdi+E8hOuxzBBM6e0hP+OoFjbbGXyIEsfduKjbyBANTnAJH+6QAzer7qntdTk8K8okqMmy+Exn2ZPlbZ9zR8PYkwQoooTU/rdTQ4L945EitYjuq5dM8GbkwkMd1S+u6PyY1rUPdrFFz0aTBpKNzdaCNvm6JuIWhsskIBl65WwzNfIJvKg6sOfUXrUg80BF+Z/toD2KLYprFPz6mtQCa7sYDm08Z3YmPNo4vTBgSb9pGbBjayx3CtlIuDrMHK1LvoWgW2vP2gq12rvXua7vZGhaZ2M3GpFVBVR6RNaJdCbfytXtRCkZE=
  on:
    tags: true
    repo: jjyyxx/SchemaGenerator
    branch: master
