language: node_js
node_js:
- node
install:
- npm i
- npm i -g codecov
script:
- npm run lint
- npm run build
- npm run ci
deploy:
  - skip_cleanup: true
    provider: npm
    email: obfishstudio@gmail.com
    api_key:
      secure: "ufc1xGPxnhRfGyKH5AgvDx26O7DKx56UVQPVDp75kJr2BU/QNgs/NzYLj6iE1rW+V7yzEYS7o579+4u41Y0e2ytQNGxfsZSNBNqhB4kC6TVQA2PpyT6Tvz6pYYxZLSTnpveHbFkVzMZc4dlHKjtpjOU13YLZ+YazHvWVS1Jlf+baMq7BmEXruvH17MQc/baP4N8njqRL2UjI0kT3aZWg119lBgcUePcfPNahB471aQlX7875Q+yQOAiOtLvHt9nMDEjynHRAp9hUB5v23DCSLRhIaphR0tc3SuHhtJ7qP//GAY1wtZbSvovPHI22VBHNYyxTsKraaBv7eV0AuBDM4Wh+ig98xVe7ezXLw4yXAywdqMd0Q3av1pctiSbgJFuzK3rs/JTtU9H3vSYN1DGNN/BO8LAeV7lrIb0u36Wh7YlR7vCFoe8EBOs2tGPvwkMcxOLNO4qKnhL96mo2Z4Dr/6lUr82Nj74WrvAdOgyd3GjxxE6/h+Tz8xzYFwnrHI4WRDwAJUMKIHQEznceQBtjwUaFVCIv7FEf7T/uEt/5DXRlfJ8mLa1/xwFiQNdL4Li9GqmomnSl+kC+KvTErihw5irstHDNwEY3xRcULu9uKxhCAL/kb5foe68ukz2Tf8CTvKLBM4z8MdLPnSjuelVRuQfSJUon4FDn9TF/Kt5AVrs="
    on:
      tags: false
      repo: jjyyxx/JSONSchemaSimulator
      branch: develop
