language: node_js
node_js:
- node
install:
- npm i
- npm i -g codecov
script:
- npm run lint
- npm run build
- npm run ci
deploy:
  skip_cleanup: true
  provider: npm
  email: obfishstudio@gmail.com
  on:
    tags: false
    repo: jjyyxx/JSONSchemaSimulator
    branch: develop
  api_key:
    secure: U/QmEHS27WlKT7t1oh6efIsGOf18BsUfEV+ySXiSU6cfxCDVqEiz//birtHuZwisuJ2T6pwYgTBx4FGgMkxIip9NqrEzWjhIMjhKtz8+w98jwMlt7gvAFxMsuRmidCol1K2k3Q6QFrwsbgjE1bnRwObfv0repbW95WEnXmw4CDc6MMOV5q63c7aGNuPpU/jgwEY83jeLJOQsIuoCTQv0esAu9LBa3nji4F2JVuSEuwRPglrMlUrSoaoEQCKcgaA8R6+TfdLZAttJbhmK/8pvJ0lHSpW4KBdCuJTkvbIpuL5S7tRnBSZ+LUVD5LwfD86RUd7eF4m1IU0XSZRbGMbBw4u2UkugC6niLHBtsRnNDlQGY4GxxGmdMC106408U18+qYAO2M7WMbQ2eeKoQ/byWsUow/Wq5xlN9MyxlklyfKnTcnsNOi/iGhkuGogQsOQ7JgrByIJ71rZ4AVD79fuM3Kj4lVHX2LfDvHXbJDjkFBfnkwzSVpwh9NMW+otIJC7UiVtwnaL1wA7LJ04zE7ldsBGjuV3OqZUaN3kMD1wsaiFelY4HjH0/LpV0q90grVMYlInJfYna225P4X243MZuXZs+5X7vTe+d4/ic0/gGM428zBduqaC/ApPBl0+SU9WRDSaXhruXlAUm43VzU9UUS01S36XCdiecLKYqROYWdeQ=
