language: node_js
node_js:
- node
install:
- npm i
- npm i -g codecov
script:
- npm run lint
- npm run build
- npm run ci
deploy:
  - skip_cleanup: true
    provider: npm
    email: obfishstudio@gmail.com
    api_key:
      secure: "Sifw0VBuIkOCkX4BJDB48958+QkrlcBU36Ri4TpS5DLCw/viAbtzCyOmAwCCscF/BxOkki0FaxV8FNWTJEFpOCinX5kO8gHzU0sHRpXLF99GQJbdzbwUW8yTkc1vtctedp+Wp187lDQQGSJU9gEZR9QClLsceKmea/ns0XklncsE2FAzEVKuNt5oyacHPy1uQVrxvcUemOViLMpYiNaldrncx6zh8KT0L25KwjWHM5N1WGGxANb9Y3N/yTmC8i0nZI++E/rKLiWs5hksf/rL+9FEDAiWC+zBx6pChgxlR647TErnXbnrZDnXfV79CkXv7Z3cE4YQjHDKNZCs+Gs2lt5D2dtEVuljqKH/aSYQpSO7WpU7OMZSU3vxV++oWY6WTmO5a15V942cMOspaPbl28awb5sPQqVhlrKLf3756y1aMfihj8tDOzRvmJ4cusB15D9ri0VZa1PsYghPHz9ov32rAKwH3Jp61/XqzKBTdrSSbuEtcSAMwClA512g54FG7K54l0fWRfKm94jKThEpBhvof6/DIv+tHFaDI3pNKwYVaRKircvvDuAvqK1sgkxrZn/VPQxylqVueAVWVlq8DoOIWLSFggnZyMTL4pyz4G0stM4hpk7nBAuZYCHIi8lsoTVYUzrxzGL8NOj7dp2fWEM0zJYOqvwrscE0IAQ2oGM="
    on:
      tags: false
      repo: jjyyxx/JSONSchemaSimulator
      branch: develop
